# Generated by Django 5.0.6 on 2024-07-05 12:41

import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Video',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('vidTitle', models.CharField(max_length=20)),
                ('vidDescr', models.TextField()),
                ('vidFile', models.FileField(upload_to='uploads/video_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['mp4'])])),
                ('vidThumb', models.FileField(upload_to='uploads/thumb_files', validators=[django.core.validators.FileExtensionValidator(allowed_extensions=['png', 'jpg', 'jpeg'])])),
                ('vidDate', models.DateTimeField(default=django.utils.timezone.now)),
            ],
        ),
    ]
