# Generated by Django 5.0.6 on 2024-07-05 13:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='video',
            old_name='vidDate',
            new_name='Date_posted',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='vidDescr',
            new_name='Description',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='vidThumb',
            new_name='Thumbnail',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='vidTitle',
            new_name='Title',
        ),
        migrations.RenameField(
            model_name='video',
            old_name='vidFile',
            new_name='Video_file',
        ),
    ]
